#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import pymssql 


def get_conn(server, user, password, database):
	conn = pymssql.connect(server, user, password, database)
	return conn


if __name__ == '__main__':
	server = 'localhost'
	user = 'dataedw'
	password = 'dataedw'
	database = 'dataedw'
	conn = get_conn(server, user, password, database)
	cursor = conn.cursor()
	sql = '''
		SELECT * FROM TEST
	'''
	cursor.execute(sql)
	for i in cursor:
		print(i)
	conn.close()
